services:
  bot:
    build: .
    container_name: td-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./dump.json:/app/dump.json 
    secrets:
      - bot_token

secrets:
  bot_token:
    file: ./secrets/bot_token
